name: emk-frontend

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL?error}
    image: itc2026-frontend:local
    restart: unless-stopped
    ports:
      - "3000:80"
