from fastapi import APIRouter

from .v1_auth_authenticate_post import router as v1_auth_authenticate_post_router
from .v1_cabinet_document_move_post import router as v1_cabinet_document_move_post_router
from .v1_cabinet_me_get import router as v1_cabinet_me_get_router
from .v1_cabinet_documents_comment_patch import router as v1_cabinet_documents_comment_patch_router
from .v1_cabinet_document_comments_get import router as v1_cabinet_document_comments_get_router
from .v1_cabinet_document_comments_all_get import router as v1_cabinet_document_comments_all_get_router
from .v1_cabinet_document_comments_post import router as v1_cabinet_document_comments_post_router
from .v1_cabinet_document_get import router as v1_cabinet_document_get_router
from .v1_cabinet_document_file_get import router as v1_cabinet_document_file_get_router
from .v1_cabinet_document_pdf_file_get import router as v1_cabinet_document_pdf_file_get_router
from .v1_cabinet_reviews_post import router as v1_cabinet_reviews_post_router
from .v1_cabinet_document_file_post import router as v1_cabinet_document_file_post_router
from .v1_cabinet_stages_get import router as v1_cabinet_stages_get_router
from .v1_user_notifications_post import router as v1_user_notifications_post_router
from .v1_cabinet_notifications_unread_get import router as v1_cabinet_notifications_unread_get_router
from .v1_cabinet_notification_read_post import router as v1_cabinet_notification_read_post_router

router = APIRouter()

router.include_router(v1_auth_authenticate_post_router)
router.include_router(v1_cabinet_document_move_post_router)
router.include_router(v1_cabinet_me_get_router)
router.include_router(v1_cabinet_documents_comment_patch_router)
router.include_router(v1_cabinet_document_comments_get_router)
router.include_router(v1_cabinet_document_comments_all_get_router)
router.include_router(v1_cabinet_document_comments_post_router)
router.include_router(v1_cabinet_document_file_get_router)
router.include_router(v1_cabinet_document_pdf_file_get_router)
router.include_router(v1_cabinet_document_get_router)
router.include_router(v1_cabinet_reviews_post_router)
router.include_router(v1_cabinet_document_file_post_router)
router.include_router(v1_cabinet_stages_get_router)
router.include_router(v1_user_notifications_post_router)
router.include_router(v1_cabinet_notifications_unread_get_router)
router.include_router(v1_cabinet_notification_read_post_router)
