---
openapi: 3.1.0
info:
  title: Backend service
  version: 0.1.0
paths:
  /v1/auth/authenticate:
    post:
      summary: Authenticate
      operationId: authenticate_v1_auth_authenticate_post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Body_authenticate_v1_auth_authenticate_post"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1AuthAuthenticatePostResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /v1/cabinet/client:
    get:
      summary: Cabinet Client
      operationId: cabinet_client_v1_cabinet_client_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1CabinetClientGetResponse"
      security:
        - OAuth2PasswordBearer: []
  /v1/stages:
    get:
      summary: List stages
      operationId: list_stages_v1_stages_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StageWithReviewerAndDocsGetResponse"
      security:
        - OAuth2PasswordBearer: []
  /v1/stages/{id}:
    get:
      summary: Get stage by id
      operationId: get_stage_v1_stages_id_get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            title: Id
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StageGetResponse"
        "404":
          description: Stage not found
      security:
        - OAuth2PasswordBearer: []
components:
  schemas:
    Body_authenticate_v1_auth_authenticate_post:
      properties:
        grant_type:
          anyOf:
            - type: string
              pattern: ^password$
            - type: "null"
          title: Grant Type
        username:
          type: string
          title: Username
        password:
          type: string
          format: password
          title: Password
        scope:
          type: string
          title: Scope
          default: ""
        client_id:
          anyOf:
            - type: string
            - type: "null"
          title: Client Id
        client_secret:
          anyOf:
            - type: string
            - type: "null"
          format: password
          title: Client Secret
      type: object
      required:
        - username
        - password
      title: Body_authenticate_v1_auth_authenticate_post
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    V1AuthAuthenticatePostResponse:
      properties:
        access_token:
          type: string
          title: Access Token
        token_type:
          type: string
          title: Token Type
      type: object
      required:
        - access_token
        - token_type
      title: V1AuthAuthenticatePostResponse
    V1CabinetClientGetResponse:
      properties:
        fio:
          type: string
          title: Fio
        login:
          type: string
          title: Login
      type: object
      required:
        - fio
        - login
      title: V1CabinetClientGetResponse
    User:
      properties:
        user_id:
          type: string
          title: User Id
        login:
          type: string
          title: Login
        fio:
          type: string
          title: Fio
        scope:
          type: string
          title: Scope
      type: object
      required:
        - user_id
        - login
        - fio
        - scope
      title: User
    StageGetResponse:
      properties:
        stage_id:
          type: integer
          title: Stage Id
        next_stage:
          type: integer
          title: Next Stage
        title:
          type: string
          title: Title
        docs:
          type: array
          items:
            type: object
            additionalProperties: true
          title: Docs
        reviewers:
          type: array
          items:
            $ref: "#/components/schemas/User"
          title: Reviewers
      type: object
      required:
        - stage_id
        - next_stage
        - title
        - docs
        - reviewers
      title: StageGetResponse
    StageSummaryGetResponse:
      properties:
        stage_id:
          type: integer
          title: Stage Id
        next_stage:
          type: integer
          title: Next Stage
        title:
          type: string
          title: Title
      type: object
      required:
        - stage_id
        - next_stage
        - title
      title: StageSummaryGetResponse
    StageWithReviewerAndDocsGetResponse:
      properties:
        stage:
          $ref: "#/components/schemas/StageSummaryGetResponse"
        docs:
          type: array
          items:
            type: object
            additionalProperties: true
          title: Docs
        reviewers:
          type: array
          items:
            $ref: "#/components/schemas/User"
          title: Reviewers
      type: object
      required:
        - stage
        - docs
        - reviewers
      title: StageWithReviewerAndDocsGetResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: /v1/auth/authenticate
